(()=>{
  const siteHeader=document.querySelector('.header');if(siteHeader){const setHeader=()=>siteHeader.classList.toggle('is-scrolled',scrollY>12);setHeader();addEventListener('scroll',setHeader,{passive:true})}
  const menu=document.querySelector('.menu'),nav=document.querySelector('nav');if(menu&&nav)menu.onclick=()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))};
  const products=[
    {id:'pecans',name:'Orchard Select Pecans',type:'pecan',grower:'Red Ridge Orchard',note:'Whole native pecans · Sample listing',copy:'A sample listing pattern for whole native pecans with an easy route to pickup or a producer-managed contact channel.'},
    {id:'meal',name:'Pecan Meal',type:'pecan',grower:'Cedar Bend Farm',note:'Stone-ground baking staple · Sample listing',copy:'A sample listing for a pantry staple, with clear category, grower and availability information.'},
    {id:'field-box',name:'Seasonal Field Box',type:'produce',grower:'Willow Creek Growers',note:'Rotating specialty crops · Sample listing',copy:'A sample seasonal-box page that can explain changing contents without making stale inventory promises.'},
    {id:'herbs',name:'Herb Bundle',type:'produce',grower:'Prairie Sky Farm',note:'Fresh culinary herbs · Sample listing',copy:'A sample product card that leads visitors directly to the producer story and pickup route.'},
    {id:'honey',name:'Wildflower Honey',type:'pantry',grower:'Honey Hollow Apiary',note:'Small-batch raw honey · Sample listing',copy:'A sample pantry listing, designed for local food details and producer-managed sales routes.'},
    {id:'preserve',name:'Summer Preserve',type:'pantry',grower:'Three Sisters Garden',note:'Seasonal fruit preserve · Sample listing',copy:'A sample seasonal preserve listing with a clear connection back to the grower.'}
  ];
  const params=new URLSearchParams(location.search),selectedProduct=products.find(x=>x.id===params.get('item'))||products[0];
  const setText=(id,value)=>{const node=document.querySelector(id);if(node)node.textContent=value};
  setText('#productName',selectedProduct.name);setText('#productBy',`From ${selectedProduct.grower} · Sample listing`);setText('#productCopy',selectedProduct.copy);setText('#productCategory',selectedProduct.type==='pecan'?'Native pecans':selectedProduct.type==='produce'?'Specialty crops':'Pantry goods');
  const growerRoute={"Red Ridge Orchard":"red-ridge","Cedar Bend Farm":"cedar-bend","Willow Creek Growers":"willow-creek","Prairie Sky Farm":"prairie-sky","Honey Hollow Apiary":"honey-hollow","Three Sisters Garden":"three-sisters"};document.querySelector('#productName')&&document.querySelector('.detail-copy .button.gold')?.setAttribute('href',`story.html?grower=${growerRoute[selectedProduct.grower]}`);
  let type='all';const pg=document.querySelector('#productGrid');function renderProducts(){if(!pg)return;let list=products.filter(x=>type==='all'||x.type===type);if(document.querySelector('#sortProducts').value==='name')list=[...list].sort((a,b)=>a.name.localeCompare(b.name));pg.innerHTML=list.map(x=>`<article class="listing"><span class="tag">${x.type==='pecan'?'Native pecans':x.type==='produce'?'Specialty crops':'Pantry goods'}</span><h3>${x.name}</h3><p>${x.note}</p><div class="listingbottom"><a class="textlink" href="product.html?item=${x.id}">View details →</a><button class="save" type="button">♡ Save</button></div></article>`).join('');document.querySelector('#productCount').textContent=`Showing ${list.length} sample listing${list.length===1?'':'s'}`;pg.querySelectorAll('.save').forEach(b=>b.onclick=()=>{b.classList.toggle('saved');b.textContent=b.classList.contains('saved')?'♥ Saved':'♡ Save'})}
  document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');type=b.dataset.filter;renderProducts()});document.querySelector('#sortProducts')?.addEventListener('change',renderProducts);renderProducts();
  const growers=[
    {id:'red-ridge',name:'Red Ridge Orchard',tags:['pecan','pollinator'],place:'Pontotoc County',desc:'Native pecans, understory habitat and careful orchard management.',harvest:'Native pecans',practice:'Habitat, mulch, orchard care'},
    {id:'willow-creek',name:'Willow Creek Growers',tags:['produce','pollinator'],place:'Murray County',desc:'Seasonal vegetables grown with cover crops and compost.',harvest:'Seasonal vegetables',practice:'Cover crops, compost'},
    {id:'cedar-bend',name:'Cedar Bend Farm',tags:['pecan'],place:'Garvin County',desc:'Heirloom pecans and pantry staples from a family-run orchard.',harvest:'Heirloom pecans',practice:'Orchard-floor care'},
    {id:'three-sisters',name:'Three Sisters Garden',tags:['produce','pollinator'],place:'Johnston County',desc:'Specialty vegetables, flowers and food for community tables.',harvest:'Specialty crops',practice:'Flowers, diverse crops'},
    {id:'honey-hollow',name:'Honey Hollow Apiary',tags:['pollinator'],place:'Carter County',desc:'Local honey and pollinator habitat woven into a working farm.',harvest:'Honey & pantry goods',practice:'Pollinator habitat'},
    {id:'prairie-sky',name:'Prairie Sky Farm',tags:['produce'],place:'Coal County',desc:'Culinary herbs and seasonal crops grown on a small scale.',harvest:'Herbs & specialty crops',practice:'Small-scale stewardship'}
  ];
  const selectedGrower=growers.find(x=>x.id===params.get('grower'))||growers[0];setText('#storyName',selectedGrower.name);setText('#storyLocation',`${selectedGrower.place} · ${selectedGrower.harvest}`);setText('#storyCopy',`This fictional profile shows how ${selectedGrower.name} could explain its harvest and land-care approach. ${selectedGrower.desc} In production, the grower can update this CMS-managed profile.`);setText('#storyHarvest',selectedGrower.harvest);setText('#storyPractice',selectedGrower.practice);
  let pf='all';const gd=document.querySelector('#producerGrid');function renderGrowers(){if(!gd)return;const q=document.querySelector('#producerSearch').value.toLowerCase();const list=growers.filter(x=>(pf==='all'||x.tags.includes(pf))&&`${x.name} ${x.place} ${x.desc} ${x.tags.join(' ')}`.toLowerCase().includes(q));gd.innerHTML=list.map(x=>`<article class="producer"><span class="tag">${x.place}</span><h3>${x.name}</h3><p>${x.desc}</p><div class="meta">${x.tags.map(t=>`<span>${t==='pecan'?'Native pecans':t==='produce'?'Specialty crops':'Pollinator habitat'}</span>`).join('')}</div><a class="link-card" href="story.html?grower=${x.id}">Read story →</a></article>`).join('')||'<p>No sample producers match that search.</p>'}
  document.querySelector('#producerSearch')?.addEventListener('input',renderGrowers);document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');pf=b.dataset.pfilter;renderGrowers()});renderGrowers();
  const modal=document.querySelector('#modal');document.querySelector('[data-open]')?.addEventListener('click',()=>modal.classList.add('open'));document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.classList.remove('open'));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
  const f=document.querySelector('#applicationForm');if(f){let step=1;const show=n=>{step=n;f.querySelectorAll('.formstep').forEach(x=>x.classList.toggle('active',+x.dataset.step===step));document.querySelectorAll('.steps li').forEach((x,i)=>x.classList.toggle('current',i===step-1));if(step===3){const d=new FormData(f);document.querySelector('#summary').innerHTML=`<p><b>Operation:</b> ${d.get('farm')}</p><p><b>Contact:</b> ${d.get('contact')} · ${d.get('email')}</p><p><b>Location:</b> ${d.get('location')}</p><p><b>Crops:</b> ${d.getAll('crops').join(', ')||'Not selected'}</p><p><b>Practice note:</b> ${d.get('practice')||'—'}</p>`}};f.querySelectorAll('.next').forEach(b=>b.onclick=()=>{const fields=[...f.querySelector(`[data-step="${step}"]`).querySelectorAll('[required]')];if(fields.some(x=>!x.reportValidity()))return;show(step+1)});f.querySelectorAll('.prev').forEach(b=>b.onclick=()=>show(step-1));f.onsubmit=e=>{e.preventDefault();const d=new FormData(f),text=`Sample Producer Program Summary\nOperation: ${d.get('farm')}\nContact: ${d.get('contact')}\nEmail: ${d.get('email')}\nLocation: ${d.get('location')}\nCrops: ${d.getAll('crops').join(', ')||'Not selected'}\nPractice: ${d.get('practice')||'Not provided'}`,a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='sample-producer-summary.txt';a.click();URL.revokeObjectURL(a.href);f.querySelectorAll('.formstep').forEach(x=>x.classList.remove('active'));f.querySelector('.success').classList.add('show')}}
})();
